dist: trusty
sudo: false
language:
  - c
  - c++
compiler:
  - gcc
  - clang
env:
  global:
    - GOOGLETEST_VERSION=1.8.0
    - NANOPB_VERSION=58af4d1fb733c5348b68dd3980f2a230d95400b4
  matrix:
    - PROTOBUF_VERSION=2.6.1
    - PROTOBUF_VERSION=3.1.0
install: ./.travis-install.sh
script: ./.travis-script.sh
